#!/usr/bin/env python3
"""Install an UNTRACKED hook shim that survives checking out an old commit.

Written after a lane worktree's HEAD moved and nothing recorded who moved it.

## The problem the tracked hook cannot solve

`core.hooksPath=.githooks` points inside the working tree, and git runs
`post-checkout` **after** the tree has been updated. So the hook that runs is
the destination commit's hook, not the source's. Check out anything cut before
the audit landed and the audit does not exist to run — the tree does not carry
it, and neither does the repo's copy of the audit script.

That is not a marginal branch population. It is exactly the incident's shape:
`git -C <project>-lane3 checkout --detach origin/feat/<older-branch>` lands a
tree with neither file and records nothing, which is the one move attribution
most needs.

## The shim

`<git-common-dir>/lane-hooks/` is outside every working tree, so no checkout
can swap or remove it. `core.hooksPath` points there instead. Each wrapper:

  1. records the audit (post-checkout only), from a copy of `lane3_audit.py`
     that also lives in the common dir and is likewise checkout-proof; then
  2. execs the tracked `.githooks/<name>` if the destination tree has one.

So the tracked hooks keep working and keep being the place their logic lives —
`.githooks/post-checkout` still does the `sync_rules` link sync, and editing it
still takes effect. The shim adds exactly one guarantee: the audit line runs
whatever the destination tree contains.

Re-run after changing `.githooks/`: a new hook needs a new wrapper. `mise run
hooks-install` does that, and running this twice is harmless.
"""
from __future__ import annotations

import argparse
import shutil
import stat
import subprocess
import sys
from pathlib import Path

WRAPPER_DIR_NAME = "lane-hooks"

#: Wrappers are generated for every tracked hook, plus these — `post-checkout`
#: must exist even in a repo whose `.githooks/` does not carry one yet, because
#: recording the move is the entire point.
ALWAYS = ("post-checkout",)

_AUDIT_LINE = '''# Record BEFORE delegating, so a destination tree that predates the
# audit still gets attributed. This copy lives in the git common dir and cannot
# be swapped by a checkout.
if [ -f "{audit}" ]; then
  python3 "{audit}" record --event post-checkout --outcome moved \\
    --prior-head "$1" --target "$2" >/dev/null 2>&1 || true
fi
'''

_WRAPPER = '''#!/bin/bash
# GENERATED by harmonic-forge tools/lane/install_lane_hooks.py. Do not edit.
# Untracked on purpose: a checkout must not be able to remove the audit.
{audit_block}
tracked="$(git rev-parse --show-toplevel 2>/dev/null)/.githooks/{name}"
if [ -x "$tracked" ]; then
  exec "$tracked" "$@"
fi
exit 0
'''


def _git(*args: str, cwd: Path | None = None) -> str | None:
    try:
        result = subprocess.run(["git", *args], cwd=str(cwd) if cwd else None,
                                capture_output=True, text=True, timeout=15)
    except (OSError, subprocess.SubprocessError):
        return None
    return result.stdout.strip() if result.returncode == 0 else None


def install(repo: Path) -> tuple[Path, list[str]]:
    common = _git("rev-parse", "--git-common-dir", cwd=repo)
    if common is None:
        raise SystemExit(f"not a git repository: {repo}")
    common_path = Path(common)
    if not common_path.is_absolute():
        common_path = repo / common_path

    # The platform's canonical copy (harmonic-forge#720), not the consuming
    # repo's `scripts/lane3_audit.py`, which is now a one-release shim.
    audit_src = Path(__file__).resolve().parent / "lane3_audit.py"
    audit_dst = common_path / "lane3_audit.py"
    if audit_src.is_file():
        shutil.copy2(audit_src, audit_dst)

    tracked_dir = repo / ".githooks"
    names = sorted({p.name for p in tracked_dir.iterdir() if p.is_file()}
                   if tracked_dir.is_dir() else set())
    names = sorted(set(names) | set(ALWAYS))

    wrapper_dir = common_path / WRAPPER_DIR_NAME
    wrapper_dir.mkdir(parents=True, exist_ok=True)
    for name in names:
        audit_block = (_AUDIT_LINE.format(audit=audit_dst)
                       if name == "post-checkout" else "")
        target = wrapper_dir / name
        target.write_text(_WRAPPER.format(name=name, audit_block=audit_block),
                          encoding="utf-8")
        target.chmod(target.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP)

    _git("config", "core.hooksPath", str(wrapper_dir), cwd=repo)
    return wrapper_dir, names


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", default=".", help="repository to install into")
    args = parser.parse_args(argv)
    wrapper_dir, names = install(Path(args.repo).resolve())
    print(f"[lane-hooks] core.hooksPath -> {wrapper_dir}")
    print(f"[lane-hooks] wrappers: {', '.join(names)} (each delegates to .githooks/)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
