#!/usr/bin/env python3
"""Emit or atomically capture the current-milestone summary (hrse#1210/#1232)."""
from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from forge_pipeline_triage import (
    render_summary_failure, render_summary_section, run_triage,
)
from milestone_summary_analysis import dependencies, file_scope, tooling_marker
from milestone_summary_render import _intersection, render
from milestone_summary_source import (
    FETCH_LIMIT, MILESTONE_REPOS, NO_MILESTONE_REPO, REPO_PREFIX, board_fields,
    cache_dir, gh_json, known_milestones, milestone_counts, read_anchor,
    resolve_milestone, rewrite_anchor, working_tree_dirty,
)

CAPTURE_HEADER = (
    "<!-- DO NOT EDIT — generated by milestone_summary.py --capture (H1232); "
    "never merge to main -->"
)


def fetch_issues(repo: str, milestone: str | None) -> list[dict]:
    """Compatibility facade whose GitHub call remains patchable by tests."""
    args = ["issue", "list", "--repo", repo, "--state", "open", "--limit",
            str(FETCH_LIMIT), "--json",
            "number,title,body,labels,updatedAt,milestone,comments"]
    if milestone:
        args += ["--milestone", milestone]
    issues = gh_json(*args)
    if len(issues) >= FETCH_LIMIT:
        raise SystemExit(f"sprint-plan summary: {repo} result is truncated at {FETCH_LIMIT}.")
    return issues


class Cache:
    """Compatibility facade preserving patchable cache/file-scope seams."""
    def __init__(self, enabled: bool = True, rewrite: bool = False) -> None:
        self.path = cache_dir() / "file_scope.json"
        self.enabled, self.rewrite = enabled, rewrite
        self.data = {}
        if enabled:
            try:
                self.data = json.loads(self.path.read_text())
            except (OSError, ValueError):
                self.data = {}
        self.fresh = self.cached = 0

    def scope(self, repo: str, issue: dict) -> list[str]:
        key = f"{repo}#{issue['number']}"
        entry = self.data.get(key)
        if self.enabled and entry and entry.get("updated_at") == issue.get("updatedAt"):
            self.cached += 1
            return entry["scope"]
        scope = file_scope(issue)
        self.data[key] = {"updated_at": issue.get("updatedAt"), "scope": scope}
        self.fresh += 1
        return scope

    def save(self) -> None:
        if not (self.enabled or self.rewrite):
            return
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_text(json.dumps(self.data, indent=2, sort_keys=True))


def collect(repo: str, cache: Cache,
            fields: dict[tuple[str, int], dict[str, str]]) -> list[dict]:
    prefix = REPO_PREFIX[repo.split("/")[-1]]
    records = []
    for issue in fetch_issues(repo, None):
        board = fields.get((repo, issue["number"]), {})
        if board.get("Status", "Todo") == "Done":
            continue
        scope = cache.scope(repo, issue)
        records.append({
            "key": f"{prefix}{issue['number']}", "repo": repo,
            "number": issue["number"], "title": issue["title"],
            "milestone": (issue.get("milestone") or {}).get("title"),
            "fields": board, "deps": dependencies(repo, issue), "scope": scope,
            "tooling": tooling_marker(issue, scope),
            # hrse#1584: `lane_state.classify()` reads these. Deliberately
            # NOT cached alongside `scope`: a new comment is exactly what
            # moves lane state, and it rides the same fetch at no extra
            # request, so there is nothing to save by caching it.
            "comments": issue.get("comments") or [],
        })
    return records


def capture(path: Path, summary: str) -> None:
    """Atomically persist the generated-file warning, a captured_at
    timestamp (hrse#1390 -- the renderer's Sprint summary freshness stamp;
    distinct from the page's own render time, which can differ by hours),
    and the exact stdout bytes.

    This makes the written file always byte-differ run-to-run, so
    `publish_sprint_summary.py`'s unchanged-file no-op path (still tested by
    `test_unchanged_capture_still_dispatches`) is now practically
    unreachable in normal operation -- accepted, matching
    `publish_dev_status.py`'s existing per-run-timestamp behavior
    (hrse#213 precedent), not a regression."""
    path.parent.mkdir(parents=True, exist_ok=True)
    captured_at = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
    handle = tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=path.parent,
                                         delete=False, suffix=".tmp", newline="")
    temporary = Path(handle.name)
    try:
        handle.write(CAPTURE_HEADER + "\n" + f"<!-- captured_at: {captured_at} -->\n" + summary + "\n")
        handle.flush()
        os.fsync(handle.fileno())
        handle.close()
        os.replace(temporary, path)
    except BaseException:
        handle.close()
        temporary.unlink(missing_ok=True)
        raise


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--priorities", type=Path, default=Path("docs/PRIORITIES.md"))
    parser.add_argument("--milestone")
    parser.add_argument("--no-cache", action="store_true")
    parser.add_argument("--reconcile", action="store_true")
    parser.add_argument("--no-summary", dest="reconcile_only", action="store_true")
    parser.add_argument("--reconcile-only", dest="reconcile_only", action="store_true")
    parser.add_argument("--capture", type=Path,
                        help="atomically capture generated output for the metrics branch")
    args = parser.parse_args(argv)
    anchor = args.milestone or read_anchor(args.priorities)
    milestone, correction = resolve_milestone(
        anchor, milestone_counts(MILESTONE_REPOS), known_milestones(MILESTONE_REPOS))
    if correction:
        print(f"[sprint-plan] {correction}", file=sys.stderr)
        if args.reconcile:
            if working_tree_dirty(args.priorities):
                raise SystemExit(f"sprint-plan summary: {args.priorities} has uncommitted changes. Commit or stash first.")
            rewrite_anchor(args.priorities, milestone)
            print(f"[sprint-plan] the release thesis was dropped from the heading — "
                  f"{milestone}'s thesis is not the previous release's. Write the "
                  "new one before committing.", file=sys.stderr)
            print(f"[sprint-plan] rewrote the anchor in {args.priorities} — commit locally, do not merge while implementation branches are open.", file=sys.stderr)
    if args.reconcile_only:
        return
    cache = Cache(enabled=not args.no_cache, rewrite=args.no_cache)
    fields = {**board_fields("vitalharmony", 1), **board_fields("vitalharmony", 3)}
    records, blanks = [], []
    for repo in MILESTONE_REPOS:
        for record in collect(repo, cache, fields):
            if record["milestone"] == milestone:
                records.append(record)
            elif record["milestone"] is None:
                blanks.append(record)
    forge = collect(NO_MILESTONE_REPO, cache, fields)

    # hrse#1477. `run_triage()` is called independently rather than reusing
    # `collect()`'s records: `collect()` discards bodies and labels (which the
    # ranking rule needs) and drops `Status == "Done"` board items, and
    # narrowing the reference set that way is the change whose 6 -> 0 citation
    # collapse `classify()`'s docstring records.
    #
    # `BaseException`, not `Exception`: every failure path inside
    # `run_triage()` — `resolve_milestone`, `known_milestones`,
    # `milestone_counts`, `fetch_issues` — fails closed via `SystemExit`,
    # which is NOT a subclass of `Exception`. A bare `except Exception` here
    # would catch none of them, the summary would abort before `print()`, and
    # on the 6-hour unattended timer that is indistinguishable from "nothing
    # changed". `KeyboardInterrupt` is re-raised so Ctrl-C still works.
    try:
        entries = run_triage(milestone=milestone, board_fields=fields)
        pipeline_section = render_summary_section(entries, milestone)
    except KeyboardInterrupt:
        raise
    except BaseException as exc:  # noqa: BLE001 - see above
        pipeline_section = render_summary_failure(exc)

    summary = render(records, milestone, correction, cache, blanks, forge,
                     {r["key"] for r in records + blanks + forge},
                     pipeline_section)
    print(summary)
    if args.capture:
        capture(args.capture, summary)
    cache.save()


if __name__ == "__main__":
    main()
